"""Synthetic restaurant supply catalog generator for Elephant.

Generates deterministic CSV catalogs for development and testing:
- data/catalog_sample.csv (~50 rows)
- data/catalog_full.csv (~800 rows, ~160 per store)
"""

import csv
import random
from pathlib import Path
from typing import Dict, List, Tuple

ROOT_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT_DIR / "data"

STORES = ["bebidas", "abarrotes", "carnes_frias", "carnes", "utensilios"]
UNITS = ["pieza", "kg", "litro", "caja", "costal"]

# Base catalog items per store: (name, brand, unit, pack_size, base_price, stock_hint, description)
# Rich colloquial descriptions with restaurant keywords and synonyms.
STORE_TEMPLATES: Dict[str, List[Tuple[str, str, str, float, float, int, str]]] = {
    "bebidas": [
        (
            "Refresco Cola Regular 355ml",
            "Coca-Cola",
            "caja",
            24.0,
            380.0,
            45,
            "Refresco de cola en lata 355ml caja de 24 piezas. Soda fria para servicio en mesa y venta individual.",
        ),
        (
            "Refresco Cola Sin Azucar 355ml",
            "Coca-Cola",
            "caja",
            24.0,
            390.0,
            30,
            "Refresco de cola zero sin azucar lata 355ml pack 24. Opcion light para comensales y refresco embotellado.",
        ),
        (
            "Refresco Sabor Manzana 355ml",
            "Manzana Lift",
            "caja",
            24.0,
            360.0,
            2,  # low stock
            "Refresco sabor manzana en lata 355ml caja 24 pzas. Chesco dulce para taquerias y loncherias.",
        ),
        (
            "Refresco Toronja 355ml",
            "Squirt",
            "caja",
            24.0,
            370.0,
            40,
            "Refresco sabor toronja lata 355ml caja de 24. Ideal para preparar palomas con tequila o micheladas.",
        ),
        (
            "Agua Mineral con Gas 355ml",
            "Penafiel",
            "caja",
            24.0,
            340.0,
            35,
            "Agua mineral de manantial gasificada en lata 355ml. Sifoncito mineral para mezclas y cocteleria.",
        ),
        (
            "Agua Mineral 600ml",
            "Topochico",
            "caja",
            24.0,
            420.0,
            25,
            "Agua mineral de vidrio 600ml caja 24 botellas. Agua gasificada premium para mesa de restaurante.",
        ),
        (
            "Agua Purificada sin Gas 500ml",
            "Ciel",
            "caja",
            24.0,
            210.0,
            60,
            "Agua embotellada natural sin gas pet 500ml paquete 24 piezas. Agua pura para hidratacion de clientes.",
        ),
        (
            "Agua Purificada Garrafon 20L",
            "Bonafont",
            "pieza",
            20.0,
            55.0,
            50,
            "Garrafon de agua purificada ligera 20 litros. Agua en bidon para consumo de cocina y cafetera.",
        ),
        (
            "Cerveza Clara Lager 355ml",
            "Corona Extra",
            "caja",
            24.0,
            480.0,
            55,
            "Cerveza clara tipo lager botella 355ml cartocito de 24 chelas. Cerveza mexicana para maridaje.",
        ),
        (
            "Cerveza Ambar Viena 355ml",
            "Victoria",
            "caja",
            24.0,
            490.0,
            3,  # low stock
            "Cerveza ambar de barril en botella 355ml caja 24. La chela viena tradicional para tacos y garnachas.",
        ),
        (
            "Cerveza Oscura Negra 355ml",
            "Modelo Especial",
            "caja",
            24.0,
            510.0,
            28,
            "Cerveza oscura tipo munich lata 355ml caja 24. Cerveza negra para cortes de carne y asador.",
        ),
        (
            "Jugo de Naranja Natural 1L",
            "Jumex",
            "pieza",
            1.0,
            38.0,
            40,
            "Jugo pasteurizado sabor naranja tetra pak 1 litro. Zumo citrico para desayunos buffet y cocteleria.",
        ),
        (
            "Jugo de Manzana 1L",
            "Del Valle",
            "pieza",
            1.0,
            36.0,
            35,
            "Jugo dulce de manzana 1L tetra brik. Nectar de fruta para barra infantil y desayunos.",
        ),
        (
            "Jugo de Tomate y Almeja 946ml",
            "Clamato",
            "pieza",
            0.95,
            65.0,
            50,
            "Jugo de tomate sazonado clamato 946ml. Mezclador indispensable para micheladas cubanas y mariscos.",
        ),
        (
            "Salsa Inglesa Preparada 1L",
            "Crosse & Blackwell",
            "litro",
            1.0,
            110.0,
            20,
            "Salsa tipo inglesa liquida botella de 1 litro. Sazonador liquido para barra de bar y micheladas.",
        ),
        (
            "Salsa Jugo Sazonador 1L",
            "Maggi",
            "litro",
            1.0,
            135.0,
            22,
            "Jugo sazonador concentrado 1 litro. Salsa de soya y condimento para bebidas preparadas y carnes.",
        ),
        (
            "Jarabe Natural Liquido 1L",
            "Monin",
            "litro",
            1.0,
            180.0,
            15,
            "Jarabe natural de azucar de cana botella 1L. Almibar simple para cocteles clericot y limonadas.",
        ),
        (
            "Jarabe de Granadina 1L",
            "Madrileña",
            "litro",
            1.0,
            145.0,
            18,
            "Jarabe sabor granadina roja 1 litro. Endulzante con color para tequila sunrise y sodas italianas.",
        ),
        (
            "Vino Tinto de Mesa 750ml",
            "L.A. Cetto",
            "pieza",
            0.75,
            165.0,
            24,
            "Vino tinto cabernet sauvignon valle de guadalupe 750ml. Vino de la casa para copeo y maridaje de carne.",
        ),
        (
            "Vino Blanco de Mesa 750ml",
            "Concha y Toro",
            "pieza",
            0.75,
            140.0,
            2,  # low stock
            "Vino blanco sauvignon blanc 750ml. Vino fresco seco para copeo pastas y pescados.",
        ),
        (
            "Tequila Reposado 1L",
            "Jose Cuervo",
            "litro",
            1.0,
            320.0,
            30,
            "Tequila reposado 100% agave botella de 1 litro. Destilado de agave para margaritas y copeo en barra.",
        ),
        (
            "Mezcal Espadin Artesanal 750ml",
            "400 Conejos",
            "pieza",
            0.75,
            580.0,
            16,
            "Mezcal artesanal joven espadin oaxaca 750ml. Destilado ahumado para cocteleria de autor y sal de gusano.",
        ),
        (
            "Ron Blanco Carta Blanca 1L",
            "Bacardi",
            "litro",
            1.0,
            250.0,
            25,
            "Ron blanco tradicional botella 1 litro. Licor de cana para cubas mojitos y cocteles tropicales.",
        ),
        (
            "Vodka Clasico 1L",
            "Absolut",
            "litro",
            1.0,
            360.0,
            20,
            "Vodka destilado de trigo 1 litro. Destilado neutro premium para martinis rusos y combinados.",
        ),
        (
            "Leche Entera Ultrapasteurizada 1L",
            "Lala",
            "caja",
            12.0,
            310.0,
            40,
            "Leche entera caja con 12 litros tetra pak. Leche de vaca para espumar en cafetera y malteadas.",
        ),
        (
            "Leche Deslactosada 1L",
            "Santa Clara",
            "caja",
            12.0,
            340.0,
            30,
            "Leche deslactosada caja 12 piezas de 1 litro. Leche de facil digestion para cafe capuchino y lattes.",
        ),
        (
            "Leche de Almendra sin Azucar 1L",
            "Silk",
            "caja",
            8.0,
            360.0,
            15,
            "Bebida vegetal de almendra sin endulzar caja 8 litros. Alternativa vegana para baristas y cafeteria.",
        ),
        (
            "Te Negro en Sobres Caja 100",
            "Twinings",
            "caja",
            100.0,
            220.0,
            20,
            "Te negro english breakfast caja con 100 bolsitas. Infusion herbal caliente para servicio de salon.",
        ),
        (
            "Te Verde con Menta Caja 100",
            "McCormick",
            "caja",
            100.0,
            175.0,
            22,
            "Te verde con menta sobrecitos individuales caja 100 piezas. Infusion digestiva antioxidante.",
        ),
        (
            "Concentrado de Horchata 5L",
            "Tucan",
            "pieza",
            5.0,
            290.0,
            18,
            "Jarabe concentrado para agua fresca de horchata garrafa 5L. Rinde 25 litros agua de arroz dulce.",
        ),
        (
            "Concentrado de Jamaica 5L",
            "Tucan",
            "pieza",
            5.0,
            295.0,
            20,
            "Jarabe base flor de jamaica garrafa 5L. Concentrado de jamaica acidita para vitrolero de taqueria.",
        ),
        (
            "Refresco Sabor Naranja 355ml",
            "Fanta",
            "caja",
            24.0,
            360.0,
            35,
            "Refresco frutal sabor naranja lata 355ml paquete 24 piezas. Gaseosa naranja para combos de comida rapida.",
        ),
    ],
    "abarrotes": [
        (
            "Aceite Vegetal Comestible 20L",
            "Nutrioli",
            "pieza",
            20.0,
            780.0,
            35,
            "Aceite vegetal puro comestible cubeta de 20 litros. Aceite para freidora de restaurante papas y milanesas.",
        ),
        (
            "Aceite de Canola 5L",
            "Capullo",
            "pieza",
            5.0,
            260.0,
            40,
            "Aceite de canola puro bidon 5L. Grasa vegetal sin colesterol para salteados y plancha de cocina.",
        ),
        (
            "Aceite de Oliva Extra Virgen 5L",
            "Carbonell",
            "pieza",
            5.0,
            1150.0,
            15,
            "Aceite de oliva virgen extra lata 5 litros. Oro liquido espanol para ensaladas pastas y vinagretas.",
        ),
        (
            "Harina de Trigo Extra Fina 44kg",
            "San Antonio",
            "costal",
            44.0,
            850.0,
            25,
            "Harina de trigo de fuerza bulto o costal de 44kg. Harina panificable para masa de pizza y reposteria.",
        ),
        (
            "Harina de Maiz Nixtamalizado 20kg",
            "Maseca",
            "costal",
            20.0,
            420.0,
            30,
            "Harina de maiz nixtamalizada costal 20 kilos. Masa instantanea para tortillas sopes y gorditas.",
        ),
        (
            "Arroz Grano Largo Super Extra 25kg",
            "SOS",
            "costal",
            25.0,
            680.0,
            28,
            "Arroz blanco super extra costal 25kg. Arroz que no se bate para guarnicion de arroz rojo o blanco.",
        ),
        (
            "Frijol Negro Jamapa 25kg",
            "La Merced",
            "costal",
            25.0,
            890.0,
            22,
            "Frijol negro seleccionado costal 25 kilos. Legumbre para frijoles charros de la olla o refritos.",
        ),
        (
            "Frijol Pinto Saltillo 25kg",
            "Schettino",
            "costal",
            25.0,
            840.0,
            20,
            "Frijol pinto limpio bulto de 25kg. Frijol cremoso para molletes y frijoles con veneno.",
        ),
        (
            "Azucar Estandar Morena 50kg",
            "Zulka",
            "costal",
            50.0,
            1350.0,
            18,
            "Azucar estandar de cana bulto 50 kilogramos. Endulzante basico para aguas frescas cafe y postres.",
        ),
        (
            "Sal de Mar Grano Grueso 25kg",
            "La Fina",
            "costal",
            25.0,
            230.0,
            45,
            "Sal marina en grano costal 25kg. Sal pura para sazonar cortes de carne caldos y desinfectar verduras.",
        ),
        (
            "Sal Fina Yodada y Fluorurada 1kg",
            "La Fina",
            "caja",
            20.0,
            280.0,
            40,
            "Sal de mesa fina yodada paquete caja con 20 bolsas de 1kg. Salero de mesa para servicio a comensales.",
        ),
        (
            "Mayonesa con Jugo de Limon 3.8kg",
            "McCormick",
            "pieza",
            3.8,
            340.0,
            30,
            "Mayonesa tradicional bote institucional de 3.8 kilogramos. Aderezo cremoso para tortas hamburguesas y sandwiches.",
        ),
        (
            "Salsa Catsup Institucional 3.8kg",
            "Heinz",
            "pieza",
            3.8,
            210.0,
            35,
            "Salsa de tomate catsup galon 3.8kg. Salsa dulce de jitomate para papas a la francesa y banderillas.",
        ),
        (
            "Mostaza Amarilla Clasica 3.8kg",
            "Frenchs",
            "pieza",
            3.8,
            225.0,
            25,
            "Mostaza estilo americano tarro galon 3.8kg. Condimento amarillo para hot dogs hamburguesas y aderezos.",
        ),
        (
            "Chiles Jalapenos en Escabeche Rajitas 2.8kg",
            "La Costeña",
            "pieza",
            2.8,
            165.0,
            1,  # low stock
            "Lata grande de rajas de chile verde jalapeno en escabeche con zanahorias. Chilitos para tortas y botana.",
        ),
        (
            "Chiles Chipotles Adobados 2.8kg",
            "La Costeña",
            "pieza",
            2.8,
            195.0,
            24,
            "Lata institucional chipotle en adobo dulce 2.8kg. Chile ahumado para salsas mayonesa de chipotle y tinga.",
        ),
        (
            "Pure de Tomate Condimentado 3kg",
            "Del Fuerte",
            "pieza",
            3.0,
            140.0,
            35,
            "Lata grande de pure de jitomate sazonado 3kg. Base espesa para pastas entomatadas y guisados caseros.",
        ),
        (
            "Tomate Triturado Estilo Italiano 2.5kg",
            "Mutti",
            "pieza",
            2.5,
            240.0,
            2,  # low stock
            "Lata polpa de tomate triturado 2.5kg. Pulpa de pomodoro para salsa marinara y base de pizza artesanal.",
        ),
        (
            "Pasta Espagueti No. 5 5kg",
            "Barilla",
            "caja",
            5.0,
            210.0,
            30,
            "Caja institucional de pasta spaghetti numero 5 de 5kg. Fideos de semola de trigo duro para cocina italiana.",
        ),
        (
            "Pasta Pluma Penne Rigate 5kg",
            "La Moderna",
            "caja",
            5.0,
            185.0,
            28,
            "Pasta seca corta tipo pluma o penne paquete de 5kg. Pasta para alfredo boloñesa y ensaladas frias.",
        ),
        (
            "Cafe de Grano Tueste Medio 1kg",
            "Cafe Punta del Cielo",
            "kg",
            1.0,
            310.0,
            25,
            "Cafe en grano entero de altura chiapas tueste medio 1kg. Cafe gourmet para maquina espresso de cafeteria.",
        ),
        (
            "Cafe Soluble Clasico 1kg",
            "Nescafe",
            "pieza",
            1.0,
            380.0,
            30,
            "Cafe instantaneo soluble bote de 1 kilogramo. Cafe rapido para desayunos buffet y disolucion inmediata.",
        ),
        (
            "Levadura Seca Instantanea 500g",
            "Saf-Instant",
            "pieza",
            0.5,
            85.0,
            40,
            "Levadura en polvo seca para panificacion paquete al vacio 500g. Levadura roja para masa fermentada y pizzas.",
        ),
        (
            "Oregano Seco Entero Molido 1kg",
            "Mi Pepito",
            "kg",
            1.0,
            175.0,
            20,
            "Oregano seco mexicano aromático bolsa de 1kg. Hierba de olor para pozole salsas de pizza y caldos.",
        ),
        (
            "Pimienta Negra Molida Pura 1kg",
            "McCormick",
            "kg",
            1.0,
            320.0,
            18,
            "Pimienta negra molida fina bolsa de 1 kilo. Especia para marinar cortes carnes y sazon general.",
        ),
        (
            "Ajo en Polvo Puro 1kg",
            "Badia",
            "kg",
            1.0,
            210.0,
            25,
            "Ajo seco deshidratado pulverizado 1kg. Condimento en polvo para marinados rubs de bbq y empanizados.",
        ),
        (
            "Salsa Picante Botanera 3.8L",
            "Valentina",
            "pieza",
            3.8,
            135.0,
            45,
            "Salsa picante liquida etiqueta amarilla galon 3.8L. Salsa de botella para botanas papas fritas y tacos.",
        ),
        (
            "Salsa Picante Habanera 1L",
            "El Yucateco",
            "litro",
            1.0,
            145.0,
            30,
            "Salsa extra picante de chile habanero verde botella de 1 litro. Picante bravo para cochinita y mariscos.",
        ),
        (
            "Vinagre Blanco Destilado 5L",
            "Barrilito",
            "pieza",
            5.0,
            95.0,
            50,
            "Vinagre blanco de alcohol de cana garrafa 5 litros. Desinfectante y acido para encurtidos adobos y limpieza.",
        ),
        (
            "Consome de Pollo en Polvo 5kg",
            "Knorr",
            "pieza",
            5.0,
            590.0,
            25,
            "Sazonador y consome concentrado de pollo cubeta 5kg. Polvo amarillo de sabor para arroces sopas y caldos.",
        ),
        (
            "Tortillas de Harina Grandes Burrito Paquete 50",
            "Tia Rosa",
            "caja",
            50.0,
            240.0,
            20,
            "Tortillas de harina de trigo gigantes para burritos y sincronizadas. Tortilla suave y flexible no se rompe.",
        ),
        (
            "Fritura Totopos de Maiz Frito 5kg",
            "El Mexicano",
            "caja",
            5.0,
            260.0,
            30,
            "Totopos crujientes de maiz fritos bolsa grande 5kg. Nachos chips para chilaquiles guacamole y frijoles con queso.",
        ),
    ],
    "carnes_frias": [
        (
            "Queso Tipo Americano Amarillo en Rebanadas 2.2kg",
            "Kraft",
            "pieza",
            2.2,
            285.0,
            35,
            "Queso amarillo de hamburguesa en rebanadas individuales paquete 2.2kg. Queso fundible cheddar para burgers y sandwich.",
        ),
        (
            "Queso Manchego Mexicano Barra 3kg",
            "NocheBuena",
            "pieza",
            3.0,
            580.0,
            25,
            "Queso manchego pasteurizado en bloque o barra 3kg. Queso para gratinar quesadillas molletes y sincronizadas.",
        ),
        (
            "Queso Mozzarella Rayado Especial Pizza 2kg",
            "Sorrento",
            "pieza",
            2.0,
            395.0,
            40,
            "Queso mozzarella rallado bolsa 2 kilos. Queso hebra fundente con excelente estiramiento para pizza y lasana.",
        ),
        (
            "Queso Oaxaca Hebra Fresco 3kg",
            "Flor de Alfalfa",
            "kg",
            3.0,
            520.0,
            2,  # low stock
            "Queso de hebra tipo oaxaca artesanal bola de 3 kilos. Quesillo fresco para fundir en tlayudas y costras de queso.",
        ),
        (
            "Queso Panela Tradicional Canasta 2kg",
            "Fud",
            "pieza",
            2.0,
            310.0,
            28,
            "Queso fresco de canasta panela barra 2kg. Queso blanco bajo en grasa para ensaladas nopales y asar a la plancha.",
        ),
        (
            "Jamon de Pierna de Cerdo Extra 4kg",
            "Zwan",
            "pieza",
            4.0,
            640.0,
            25,
            "Jamon de pierna horneado barra 4 kilos. Jamon rosa para rebanar en maquina para tortas y sandwiches.",
        ),
        (
            "Jamon de Pavo Virginia 3kg",
            "San Rafael",
            "pieza",
            3.0,
            540.0,
            30,
            "Jamon de pechuga de pavo virginia pieza de 3kg. Fiambre bajo en grasa embutido fino para desayunos buffet.",
        ),
        (
            "Jamon Serrano Reserva Espanol Rebanado 500g",
            "Campofrio",
            "pieza",
            0.5,
            360.0,
            3,  # low stock
            "Jamon serrano curado madurado paquete de 500g rebanado fino. Tapa espanola charcuteria fina para tablas de quesos.",
        ),
        (
            "Tocino Ahumado Rebanado Especial 1kg",
            "Fud",
            "kg",
            1.0,
            230.0,
            40,
            "Tocino ahumado de panceta de cerdo rebanado 1 kilo. Tocineta crujiente para hamburguesas huevos con tocino y guisados.",
        ),
        (
            "Tocino Grueso en Tiras Plancha 2kg",
            "Bafar",
            "kg",
            2.0,
            420.0,
            22,
            "Tocino corte grueso ahumado paquete 2kg. Tiras de tocino resistentes para envolver camarones o asar a la parrilla.",
        ),
        (
            "Salchicha de Pavo para Hot Dog 2kg",
            "Fud",
            "pieza",
            2.0,
            195.0,
            35,
            "Salchichas de pavo para jocho paquete con 40 piezas 2kg. Embutido para hot dogs infantiles y salchipulpos.",
        ),
        (
            "Salchicha para Asar con Queso 1kg",
            "Chimex",
            "kg",
            1.0,
            165.0,
            30,
            "Salchichon polaco para asar relleno con queso fundido 1kg. Salchicha parrillera asada para botana de carnita asada.",
        ),
        (
            "Chorizo Espanol Madurado Cantimpalo 1kg",
            "Tangamanga",
            "kg",
            1.0,
            380.0,
            18,
            "Chorizo tipo cantimpalo seco rebanable paquete 1kg. Embutido curado con pimenton para pizzas y tapas.",
        ),
        (
            "Chorizo Rojo Casero para Desmenuzar 2kg",
            "San Manuel",
            "kg",
            2.0,
            290.0,
            25,
            "Chorizo rojo norteno molido en tripita 2 kilos. Embutido adobado para chori-queso huevos al gusto y tacos.",
        ),
        (
            "Pepperoni Rebanado para Pizza 1kg",
            "Hormel",
            "kg",
            1.0,
            260.0,
            45,
            "Pepperoni en rodajas listas para hornear bolsa de 1 kilo. Rebanadas especiadas clasicas para pizza americana.",
        ),
        (
            "Salami de Genova Rebanado 500g",
            "Tangamanga",
            "pieza",
            0.5,
            190.0,
            20,
            "Salami italiano estilo genova rebanado fino 500 gramos. Embutido curado con pimienta para baguette y pizzas.",
        ),
        (
            "Crema de Vaca Entera Pasteurizada 4L",
            "Lala",
            "litro",
            4.0,
            290.0,
            30,
            "Crema acida de leche pura de vaca cubeta 4 litros. Crema espesa para enchiladas chilaquiles tostadas y flautas.",
        ),
        (
            "Mantequilla Sin Sal Barra Repostera 1kg",
            "Gloria",
            "kg",
            1.0,
            210.0,
            35,
            "Mantequilla pura de vaca sin sal bloque de 1 kilo. Grasa lactea para reposteria salsas francesas y plancha.",
        ),
        (
            "Mantequilla Con Sal Porciones Individuales Caja 200",
            "Lurpak",
            "caja",
            200.0,
            480.0,
            15,
            "Mantequilla porcionada en cubitos de 10g caja con 200 piezas. Mantequillitas de mesa para pan caliente y hot cakes.",
        ),
        (
            "Pastrami Ahumado New York Style 1kg",
            "Bernina",
            "kg",
            1.0,
            430.0,
            12,
            "Pastrami de pecho de res curado y ahumado especiado 1kg. Carne curada para sandwich reuben y deli judio.",
        ),
        (
            "Roast Beef Horneado Rebanado 1kg",
            "Tangamanga",
            "kg",
            1.0,
            460.0,
            2,  # low stock
            "Roast beef de res cocido termino medio jugoso rebanado 1 kilo. Carne fria fria o tibia para baguettes gourmet.",
        ),
        (
            "Chistorra Parrillera Vasca 1kg",
            "Obertal",
            "kg",
            1.0,
            275.0,
            20,
            "Chistorra delgada estilo navarro paquete de 1kg. Embutido fresco de cerdo con pimenton para asar o chistorra frita.",
        ),
        (
            "Queso Parmesano Reggiano Autentico 1kg",
            "Zanetti",
            "kg",
            1.0,
            690.0,
            10,
            "Queso parmesano italiano anejado en cuna o trozo 1kg. Queso duro para rallar sobre pastas finas y carpaccios.",
        ),
        (
            "Queso Azul Danesh Blue 1kg",
            "Castello",
            "kg",
            1.0,
            450.0,
            15,
            "Queso azul madurado cremoso y penetrante bloque de 1kg. Queso fuerte para aderezo blue cheese de alitas de pollo.",
        ),
        (
            "Queso Crema Barra Pastelera 1.8kg",
            "Philadelphia",
            "pieza",
            1.8,
            320.0,
            30,
            "Queso crema tipo philadelphia barra pastelera 1.8kg. Untable cremoso para sushi rollos pay de queso y dips.",
        ),
        (
            "Queso Gouda Holandes Barra 3kg",
            "Frico",
            "kg",
            3.0,
            620.0,
            20,
            "Queso gouda suave importado de holanda barra de 3 kilos. Excelente para fundir gratinar o cortar en cubos.",
        ),
        (
            "Queso Feta de Leche de Cabra 1kg",
            "Kolios",
            "kg",
            1.0,
            395.0,
            14,
            "Queso feta griego en salmuera bote de 1 kilo. Queso blanco salado quebradizo para ensalada griega y mediterranea.",
        ),
        (
            "Pechuga de Pavo Ahumada Natural 3kg",
            "Peñaranda",
            "pieza",
            3.0,
            720.0,
            18,
            "Pechuga de pavo ahumada artesanal con corteza dorada 3kg. Fiambre selecto para clubsandwich y ensaladas chef.",
        ),
        (
            "Salchicha Alemana Frankfurt Gigante 1.5kg",
            "Bernina",
            "pieza",
            1.5,
            280.0,
            25,
            "Salchicha frankfurter tipo alemana embutido grande paquete 1.5kg. Salchicha crujiente para panes jumbo de jocho.",
        ),
        (
            "Mortadela con Pistache Italiana 2kg",
            "Villani",
            "pieza",
            2.0,
            410.0,
            16,
            "Mortadela de bolonia con pistachos enteros pieza de 2kg. Embutido italiano para focaccias paninis y entradas.",
        ),
        (
            "Queso Suizo Emmental Rebanado 1kg",
            "President",
            "kg",
            1.0,
            440.0,
            22,
            "Queso suizo tipo emmental con agujeros rebanado 1kg. Queso dulce con notas a nuez para fondue y hamburguesas suizas.",
        ),
        (
            "Longaniza de Cerdo Tradicional 2kg",
            "Don Chema",
            "kg",
            2.0,
            250.0,
            28,
            "Longaniza artesanal de cerdo con chile guajillo tira de 2kg. Tira de embutido para picar en salsa verde o bistec.",
        ),
    ],
    "carnes": [
        (
            "Carne Molida de Res Especial 80-20 5kg",
            "SuKarne",
            "kg",
            5.0,
            750.0,
            30,
            "Carne molida de res 80/20 magra con grasa ideal paquete 5kg. Carne para hamburguesas jugosas albondigas y picadillo.",
        ),
        (
            "Arrachera Marinada Suave de Res 5kg",
            "SuKarne",
            "kg",
            5.0,
            1150.0,
            25,
            "Arrachera de res marinada suave y tierna caja de 5 kilos. Corte marinada para parrilladas tacos de arrachera y fajitas.",
        ),
        (
            "Pechuga de Pollo sin Piel sin Hueso 10kg",
            "Bachoco",
            "caja",
            10.0,
            1280.0,
            35,
            "Pechuga de pollo limpia deshuesada y desgrasada caja 10kg. Filete de pollo para asar empanizar o deshebrar en caldo.",
        ),
        (
            "Pierna y Muslo de Pollo Mixto 10kg",
            "Pilgrims",
            "caja",
            10.0,
            580.0,
            40,
            "Pierna y muslo de pollo fresco en corte anatomico caja 10kg. Pollo para mole guisados frito estilo kansas y consomé.",
        ),
        (
            "Alitas de Pollo Enteras para Botanera 10kg",
            "Tyson",
            "caja",
            10.0,
            920.0,
            28,
            "Alitas de pollo botaneras con punta y codillo caja 10 kilos. Alitas crudas para freir banar en bufalo bbq o mango habanero.",
        ),
        (
            "Bistec de Res Suave para Taqueria 5kg",
            "Rancho Don Juan",
            "kg",
            5.0,
            890.0,
            30,
            "Bistec de pulpa blanca de res en milanesa o rebanado paquete 5kg. Carne de res para tacos al carbon fajitas y huaraches.",
        ),
        (
            "Costilla de Res Cargada para Caldo 5kg",
            "SuKarne",
            "kg",
            5.0,
            680.0,
            20,
            "Costillar cargado de res cortado en trozos paquete 5kg. Hueso con carne con sabor concentrado para caldo de res y puchero.",
        ),
        (
            "Rib Eye Choice Calidad Importada 4kg",
            "Certified Angus Beef",
            "caja",
            4.0,
            2450.0,
            12,
            "Corte fino ribeye importado calidad angus choice paquete 4kg. Ojo de bife marmoleado para asador y cortes premium.",
        ),
        (
            "New York Steak Corte Americano 4kg",
            "Sterling Silver",
            "caja",
            4.0,
            2200.0,
            1,  # low stock
            "Corte new york strip corte americano grueso 4kg. Bife de lomo sin hueso de alta terneza para parrilla y restaurante fino.",
        ),
        (
            "Tomahawk Steak con Hueso Largo 3kg",
            "Rancho San Jose",
            "caja",
            3.0,
            1890.0,
            8,
            "Chuleton tomahawk de res con costilla larga limpia 3kg. Corte vistoso para compartir y presentacion estrella de parrilla.",
        ),
        (
            "Suadero de Res Fresco Limpio 5kg",
            "Carnes La Paz",
            "kg",
            5.0,
            720.0,
            35,
            "Suadero de res entero para confitar en manteca paquete 5kg. Carne suave con grasa para tacos de taqueria de banqueta.",
        ),
        (
            "Carne de Pastor Marinada de Cerdo 5kg",
            "El Mayoral",
            "kg",
            5.0,
            640.0,
            30,
            "Pulpa de cerdo rebanada marinada en adobo de achiote 5kg. Carne adobada lista para trompo al pastor gringas y tacos.",
        ),
        (
            "Chuleta de Cerdo Ahumada Rebanada 5kg",
            "Kowi",
            "kg",
            5.0,
            590.0,
            24,
            "Chuleta ahumada de lomo de cerdo con hueso caja 5kg. Chuletitas rosadas listas para dorar en sarten a la hawaiana.",
        ),
        (
            "Costillar de Cerdo Baby Back Ribs 5kg",
            "Smithfield",
            "caja",
            5.0,
            890.0,
            18,
            "Costillitas de cerdo baby back tiernas congeladas caja 5kg. Costillar suave para banar con salsa barbacoa estilo texas.",
        ),
        (
            "Pulpa de Cerdo en Cubos para Carnitas 5kg",
            "Kowi",
            "kg",
            5.0,
            540.0,
            28,
            "Trozos de maciza y pierna de cerdo seleccionada 5kg. Carne limpia para preparar carnitas estilo michoacan y pozole.",
        ),
        (
            "Manteca de Cerdo Pura de Cazo 10kg",
            "El Ranchero",
            "cubeta" if "cubeta" in UNITS else "caja",
            10.0,
            510.0,
            30,
            "Manteca de cerdo filtrada en cubeta de 10kg. Grasa de puerco para freir carnitas dar sabor a tamales y frijoles.",
        ),
        (
            "Chicharron Prensado Botanero Guisado 5kg",
            "Don Chema",
            "kg",
            5.0,
            680.0,
            22,
            "Chicharron prensado guisado con chile guajillo bolsa 5kg. Relleno tipico para gorditas quesadillas y tlacoyos de mercado.",
        ),
        (
            "Carne para Hamburguesa Sirloin 150g Caja 40",
            "Golden Bull",
            "caja",
            6.0,
            820.0,
            20,
            "Patty de carne de sirloin 150g congelado caja 40 piezas. Hamburguesa congelada uniforme lista para plancha comercial.",
        ),
        (
            "Filete de Tilapia sin Espinas 5kg",
            "Mar de Cortes",
            "caja",
            5.0,
            620.0,
            30,
            "Filetes de pescado blanco tilapia congelados individualmente 5kg. Filete para empapelado ceviche y tacos de pescado.",
        ),
        (
            "Camaron Pacotilla Mediano Cocido 5kg",
            "Ocean Garden",
            "caja",
            5.0,
            1450.0,
            15,
            "Camaron cocido pacotilla pelado y desvenado caja 5kg. Mariscos para coctel de camaron campechanas y ensaladas del mar.",
        ),
        (
            "Camaron U15 para Pelar Crudo 5kg",
            "Ocean Garden",
            "caja",
            5.0,
            2100.0,
            2,  # low stock
            "Camaron azul gigante con cabeza talla u15 caja 5 kilos. Camaron parrillero para aguachile empanizado y al ajillo.",
        ),
        (
            "Puntas de Filete de Res para Guisado 5kg",
            "SuKarne",
            "kg",
            5.0,
            980.0,
            18,
            "Puntas y recortes limpios de filete de res paquete 5kg. Carne tierna para puntas a la mexicana o en salsa pasilla.",
        ),
        (
            "Tuetano de Res en Canoa Canutillo 5kg",
            "Rancho Don Juan",
            "kg",
            5.0,
            490.0,
            22,
            "Huesos de res cortados a la mitad estilo canoa 5kg. Tuetano para asar al carbon con sal de grano y servir en taco.",
        ),
        (
            "Chamberete de Res con Hueso Ossobuco 5kg",
            "SuKarne",
            "kg",
            5.0,
            640.0,
            25,
            "Chamberete con tuetano cortado en rodajas 5kg. Corte para estofado largo caldo de osobuco y guisados de olla.",
        ),
        (
            "Tiras de Pollo Fajita Tender Crispy 5kg",
            "Tyson",
            "caja",
            5.0,
            690.0,
            30,
            "Tiras de pechuga de pollo marinadas tipo tenders 5kg. Tenders para freir rapido en combos infantiles y wraps.",
        ),
        (
            "Menudo Pancita de Res Limpia Precocida 5kg",
            "El Parral",
            "kg",
            5.0,
            550.0,
            20,
            "Panza de res de libro y panal cocida limpia 5kg. Pancita para menudo blanco o rojo estilo norteño o michoacano.",
        ),
        (
            "Tripa de Res Precocida para Tacos 5kg",
            "Carnes La Paz",
            "kg",
            5.0,
            630.0,
            24,
            "Tripitas de res lavadas hervidas listas para dorar 5kg. Tripa dorada o tierna crujiente para taqueria de especialidad.",
        ),
        (
            "Lengua de Res Entera Limpia 3kg",
            "Rancho San Jose",
            "pieza",
            3.0,
            960.0,
            3,  # low stock
            "Lengua de res entera fresca empacada al vacio 3kg. Lengua suave para tacos en salsa verde vinagreta o a la veracruzana.",
        ),
        (
            "Costilla de Cerdo en Trozos para Fritanga 5kg",
            "Kowi",
            "kg",
            5.0,
            580.0,
            25,
            "Costillitas de puerco troceadas en cubos pequenos 5kg. Costilla para salsa verde con verdolagas y adobos caseros.",
        ),
        (
            "Molida de Pollo Magra de Pechuga 5kg",
            "Bachoco",
            "kg",
            5.0,
            640.0,
            22,
            "Carne molida 100% pechuga de pollo sin grasa 5kg. Proteina ligera para hamburguesas fitness y albondigas dieteticas.",
        ),
        (
            "Cabeza de Lomo de Cerdo Boneless 5kg",
            "Smithfield",
            "kg",
            5.0,
            560.0,
            28,
            "Cabeza de lomo deshuesada marmoleada de puerco 5kg. Trozo jugoso para pulled pork estilo bbq o asados al horno.",
        ),
        (
            "Milanesa de Res de Pulpa Negra 5kg",
            "SuKarne",
            "kg",
            5.0,
            920.0,
            26,
            "Milanesas delgadas de pulpa negra sin nervio paquete 5kg. Filetes listos para empanizar tortas y tacos acorazados.",
        ),
    ],
    "utensilios": [
        (
            "Espatula Parrillera de Acero Inoxidable 20cm",
            "Tramontina",
            "pieza",
            1.0,
            165.0,
            35,
            "Espatula parrillera de acero mango de madera remachado 20cm. Pala para aplastar hamburguesas smasheadas y voltear en plancha.",
        ),
        (
            "Cuchillo de Chef Profesional 8 Pulgadas",
            "Victorinox",
            "pieza",
            1.0,
            780.0,
            25,
            "Cuchillo cebollero santoku suizo hoja de 20cm mango fibrox. Cuchillo filoso multiusos para picar carne verdura y mise en place.",
        ),
        (
            "Cuchillo Deshuesador Curvo 6 Pulgadas",
            "Victorinox",
            "pieza",
            1.0,
            590.0,
            20,
            "Cuchillo deshuesador flexible de acero inoxidable 15cm. Hoja curva para filetear carne retirar grasa y separar hueso.",
        ),
        (
            "Pinzas de Cocina de Acero Inoxidable 40cm",
            "Vollrath",
            "pieza",
            1.0,
            120.0,
            40,
            "Tenazas pinzas largas de acero con resorte para parrillero 40cm. Pinzas para mover carbón voltear cortes y servicio en bufet.",
        ),
        (
            "Sarten de Aluminio con Antiadherente 30cm",
            "T-fal",
            "pieza",
            1.0,
            450.0,
            25,
            "Sarten uso rudo industrial con teflon reforzado 30cm. Sarten antiadherente para huevos omelettes y sellado rapido sin pegar.",
        ),
        (
            "Sarten de Hierro Fundido Curado 26cm",
            "Lodge",
            "pieza",
            1.0,
            680.0,
            15,
            "Sarten pesado de hierro fundido pre-curado 26cm. Comal para asar al horno retener calor y servir cortes calientes.",
        ),
        (
            "Olla Vaporera de Aluminio Grueso 40L",
            "Cinsa",
            "pieza",
            1.0,
            1150.0,
            12,
            "Olla vaporera de aluminio reforzado con rejilla tamalera 40 litros. Bote vaporero para tamales pozole y caldos grandes.",
        ),
        (
            "Comal Redondo de Acero al Carbon 50cm",
            "La Hacienda",
            "pieza",
            1.0,
            380.0,
            18,
            "Comal de lamina de acero para calentar tortillas y garnachas 50cm. Comal taquero redondo para taqueria y antojitos mexicanos.",
        ),
        (
            "Papel Aluminio Grado Restaurantero Rollo 400m",
            "Reynolds",
            "caja",
            1.0,
            680.0,
            30,
            "Papel aluminio institucional extra ancho rollo con 400 metros con cortador. Papel para envolver comida hornear y cubrir charolas.",
        ),
        (
            "Papel Film Plastico Adherente Rollo 600m",
            "Kirkland",
            "caja",
            1.0,
            540.0,
            28,
            "Pelicula plastica estirable transparente grado alimenticio 600m. Plastico egapack para conservar recipientes y cubrir en refrigerador.",
        ),
        (
            "Guantes de Nitrilo Negro Uso Rudo Caja 100",
            "Ammex",
            "caja",
            100.0,
            240.0,
            50,
            "Guantes desechables de nitrilo negro sin polvo caja con 100 piezas. Guantes para manipulacion higienica de alimentos y parrilladas.",
        ),
        (
            "Servilletas Interdobladas Despachador Caja 4000",
            "Kimberly-Clark",
            "caja",
            4000.0,
            520.0,
            35,
            "Servilleta interdoblada blanca para despachador de mesa caja 4000 hojas. Servilletas de papel para taquerias y restaurantes.",
        ),
        (
            "Bolsa para Basura Negra Jumbo Calibre 200 Paquete 50",
            "Reyma",
            "caja",
            50.0,
            290.0,
            40,
            "Bolsas de plastico negro para basura jumbo 90x120cm calibre pesado 50 pzas. Bolsas resistentes para botes de cocina y desperdicio.",
        ),
        (
            "Contenedor Plastico Cambro Policarbonato 12L",
            "Cambro",
            "pieza",
            12.0,
            480.0,
            20,
            "Inserto cuadrado transparente de policarbonato graduado 12 litros. Bote para mise en place fermentar masa y almacenar insumos.",
        ),
        (
            "Tapa Hermetica para Contenedor Cambro",
            "Cambro",
            "pieza",
            1.0,
            160.0,
            2,  # low stock
            "Tapa de presion hermetica para inserto cuadrado cambro. Sello antiderrame para evitar contaminacion cruzada en camara fria.",
        ),
        (
            "Inserto Sexto de Acero Inoxidable Mesa Fria",
            "Thunder Group",
            "pieza",
            1.0,
            195.0,
            35,
            "Inserto un sexto de acero inoxidable 15cm profundidad. Bandeja para barra de ensaladas salsas de mesa y linea de sandwich.",
        ),
        (
            "Tabla para Picar Polietileno Blanco 60x40cm",
            "Rubbermaid",
            "pieza",
            1.0,
            460.0,
            25,
            "Tabla de corte plastica grado sanitario blanca 60x40cm grosor 2cm. Tabla higienica que cuida el filo de cuchillos de cocina.",
        ),
        (
            "Tabla para Picar Roja para Carnes Rojas 60x40cm",
            "Rubbermaid",
            "pieza",
            1.0,
            460.0,
            22,
            "Tabla de picar plastica codigo de color rojo para carnes crudas. Evita contaminacion cruzada conforme norma de higiene alimentaria.",
        ),
        (
            "Colador Chino de Acero Malla Fina 24cm",
            "Vollrath",
            "pieza",
            1.0,
            580.0,
            15,
            "Colador conico tipo chino de acero inoxidable con mango 24cm. Tamiz para colar caldos fondos sopas y salsas tersas aterciopeladas.",
        ),
        (
            "Batidor Globo de Varillas Gruesas 35cm",
            "Winco",
            "pieza",
            1.0,
            140.0,
            30,
            "Batidor manual de alambre de acero inoxidable frances 35cm. Batidor para montar cremas mezclar vinagretas y batir salsas.",
        ),
        (
            "Cucharon para Caldo de Acero 240ml 8oz",
            "Winco",
            "pieza",
            1.0,
            110.0,
            35,
            "Cucharon dosificador de una sola pieza de acero inoxidable capacidad 8 onzas. Cucharon sopero para servir porciones exactas de pozole.",
        ),
        (
            "Pelador de Papas Industrial Ergonomico",
            "Oxo Good Grips",
            "pieza",
            1.0,
            185.0,
            40,
            "Pelador en y de navaja basculante de acero inoxidable mango de goma. Pela papas zanahorias y fruta a alta velocidad.",
        ),
        (
            "Mandolina Profesional Japonesa con Cuchillas",
            "Benriner",
            "pieza",
            1.0,
            1350.0,
            8,
            "Mandolina manual regulable de alta precision con navajas juliana. Cortadora para rebanar cebolla fina papas chip y pepino.",
        ),
        (
            "Bascula Digital Gramera Porcionadora 10kg",
            "Torrey",
            "pieza",
            1.0,
            2300.0,
            1,  # low stock
            "Bascula electronica digital para cocina capacidad 10kg precision 1g. Bascula para costeo control de mermas y porcionar proteina.",
        ),
        (
            "Termometro Digital de Lectura Instantanea Cocina",
            "ThermoPro",
            "pieza",
            1.0,
            360.0,
            25,
            "Termometro de sonda plegable para carne y freidora lectura en 3 segundos. Medidor de temperatura interna para termino de carne.",
        ),
        (
            "Soplete de Gas Butano de Reposteria y Cocina",
            "Iwatani",
            "pieza",
            1.0,
            590.0,
            16,
            "Soplete antorcha portatil con llama regulable acoplable a lata de gas. Quemador para flamear carnes dorar queso y creme brulee.",
        ),
        (
            "Charola de Aluminio para Hornear Panadera 65x45cm",
            "Nordic Ware",
            "pieza",
            1.0,
            320.0,
            35,
            "Charola panadera media hoja de aluminio calibre pesado con borde reforzado. Bandeja para hornear galletas panes o asar verduras.",
        ),
        (
            "Dispensador Dosificador de Salsa Squeeze 750ml Pack 6",
            "Tablecraft",
            "caja",
            6.0,
            190.0,
            30,
            "Botes pachiche mamila squeezebottle de plastico flexible paquete 6 piezas. Mamila para salsa catsup mostaza mayonesa o aderezos.",
        ),
        (
            "Fibra Verde Abrasiva para Lavado de Ollas Caja 24",
            "Scotch-Brite",
            "caja",
            24.0,
            220.0,
            45,
            "Esponjas fibras verdes abrasivas para tallar cochambre y sartenes caja 24. Utensilio de limpieza pesada para area de cochambre.",
        ),
        (
            "Detergente Liquido Concentrado Desengrasante 20L",
            "Axion",
            "pieza",
            20.0,
            720.0,
            20,
            "Jabon lavatrastes liquido con potente desengrasante bidon de 20 litros. Detergente concentrado para lavado de vajilla y loza.",
        ),
        (
            "Charola Termica Desechable con Tapa Paquete 100",
            "Reyma",
            "caja",
            100.0,
            280.0,
            30,
            "Contenedor desechable tipo almeja de unicel para comida corrida 100 pzas. Domo termico para comida para llevar y servicio a domicilio.",
        ),
        (
            "Vaso Desechable Cristal para Bebida Fria 16oz Caja 1000",
            "Solo Cup",
            "caja",
            1000.0,
            890.0,
            18,
            "Vasos de plastico transparente pet de 16 onzas caja con 1000 piezas. Vaso desechable para frappé refresco agua fresca y michelada.",
        ),
    ],
}


def expand_store_products(
    store: str,
    base_templates: List[Tuple[str, str, str, float, float, int, str]],
    target_count: int = 160,
) -> List[Dict[str, object]]:
    """Deterministically expands base templates into target_count distinct products."""
    products: List[Dict[str, object]] = []

    # First add all base templates (first 10 of each will form sample catalog)
    for idx, item in enumerate(base_templates):
        name, brand, unit, pack_size, price, stock, desc = item
        sku = f"{store}-{len(products) + 1:04d}"
        products.append(
            {
                "sku": sku,
                "store": store,
                "name": name,
                "brand": brand,
                "unit": unit,
                "pack_size": float(pack_size),
                "price": float(price),
                "stock": int(stock),
                "description": desc,
            }
        )

    # Modifiers to expand products systematically while preserving culinary coherence
    variants = [
        (
            "Presentacion Mayoreo",
            2.0,
            1.85,
            "Formato institucional mayoreo para alto volumen.",
        ),
        (
            "Presentacion Compacta",
            0.5,
            0.55,
            "Presentacion chica economica ideal para consumo medido.",
        ),
        (
            "Seleccion Especial",
            1.0,
            1.25,
            "Calidad seleccionada grado restaurantero premium.",
        ),
        (
            "Empaque Economico",
            1.0,
            0.85,
            "Version economica competitiva para optimizacion de costos.",
        ),
        (
            "Presentacion Familiar",
            1.5,
            1.40,
            "Empaque rinde mas con excelente relacion costo beneficio.",
        ),
    ]

    alt_brands = {
        "bebidas": ["Penafiel", "Jarritos", "Del Valle", "Tucan", "Ciel", "Bonafont"],
        "abarrotes": [
            "Great Value",
            "La Fina",
            "La Costeña",
            "McCormick",
            "San Antonio",
            "Knorr",
        ],
        "carnes_frias": ["Fud", "Bafar", "Zwan", "Chimex", "Tangamanga", "NocheBuena"],
        "carnes": [
            "SuKarne",
            "Bachoco",
            "Kowi",
            "Pilgrims",
            "Carnes La Paz",
            "Rancho Don Juan",
        ],
        "utensilios": [
            "Vollrath",
            "Tramontina",
            "Reyma",
            "Winco",
            "Rubbermaid",
            "Reynolds",
        ],
    }

    # Deterministic rotation to fill up to target_count
    var_idx = 0
    while len(products) < target_count:
        base_item = base_templates[var_idx % len(base_templates)]
        variant = variants[(var_idx // len(base_templates)) % len(variants)]
        store_brands = alt_brands[store]
        chosen_brand = store_brands[var_idx % len(store_brands)]

        name_prefix, _, unit, base_pack, base_price, base_stock, base_desc = base_item
        v_title, v_pack_mult, v_price_mult, v_desc_extra = variant

        new_pack_size = round(base_pack * v_pack_mult, 2)
        new_price = round(base_price * v_price_mult, 2)

        # Deterministic stock variation, ensuring some low stock values
        if (len(products) % 27) == 0:
            new_stock = (len(products) % 3) + 1  # yields 1, 2, or 3
        else:
            new_stock = 15 + ((var_idx * 7) % 65)

        new_name = f"{name_prefix} {v_title}"
        new_desc = f"{base_desc} {v_desc_extra}"
        sku = f"{store}-{len(products) + 1:04d}"

        products.append(
            {
                "sku": sku,
                "store": store,
                "name": new_name,
                "brand": chosen_brand,
                "unit": unit,
                "pack_size": new_pack_size,
                "price": new_price,
                "stock": new_stock,
                "description": new_desc,
            }
        )
        var_idx += 1

    return products[:target_count]


def generate_catalogs() -> Tuple[List[Dict[str, object]], List[Dict[str, object]]]:
    """Generates the full (~800 rows) and sample (~50 rows) catalogs."""
    random.seed(42)

    full_catalog: List[Dict[str, object]] = []
    sample_catalog: List[Dict[str, object]] = []

    for store in STORES:
        templates = STORE_TEMPLATES[store]
        store_products = expand_store_products(store, templates, target_count=160)
        full_catalog.extend(store_products)
        # 10 representative items per store for sample
        sample_catalog.extend(store_products[:10])

    return sample_catalog, full_catalog


def write_csv(filepath: Path, items: List[Dict[str, object]]) -> None:
    """Writes items to CSV according to the required schema."""
    fieldnames = [
        "sku",
        "store",
        "name",
        "brand",
        "unit",
        "pack_size",
        "price",
        "stock",
        "description",
    ]
    filepath.parent.mkdir(parents=True, exist_ok=True)
    with open(filepath, mode="w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        for item in items:
            writer.writerow(item)


def main() -> None:
    sample_items, full_items = generate_catalogs()

    sample_path = DATA_DIR / "catalog_sample.csv"
    full_path = DATA_DIR / "catalog_full.csv"

    write_csv(sample_path, sample_items)
    write_csv(full_path, full_items)

    print(f"Generated sample catalog: {sample_path} ({len(sample_items)} products)")
    print(f"Generated full catalog: {full_path} ({len(full_items)} products)")


if __name__ == "__main__":
    main()
